apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: linter
spec:
  tasks:
  - name: git-clone
    params:
    - name: url
      value: https://github.com/upslopeio/lint-markdown-files
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: pipeline-shared-data
  - name: linter-markdown
    params:
      - name: args
        value: ["."]
    taskRef:
      name: markdown-lint
      kind: Task
    runAfter: [git-clone]
    workspaces:
    - name: shared-workspace
      workspace: pipeline-shared-data
  workspaces:
  - name: pipeline-shared-data
